name: Push documentation to docs repo

on:
  workflow_dispatch:
  # Disable until docs/ are updated and belongs to node-ts api: https://github.com/nevermined-io/docs/issues/62
  # push:
  #   tags:
  #     - v*

jobs:
  build-and-push-to-docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.API_TOKEN_GITHUB }}
      - uses: actions/setup-node@v2
        with:
          node-version: '14.x'
      - run: npm install -g widdershins
      - name: Convert openapi JSON to MD
        run: |
          # Convert json to md
          widdershins docs/openapi.json --omitHeader -o docs/openapi.md
          echo "$(cat docs/_header.md docs/openapi.md)" > docs/node.md
          # Remove lines with pattern '*backwards compatibility*' (problematic with Docusaurus)
          sed -i '/backwards compatibility/d' docs/node.md
          rm -f docs/openapi.json docs/_header.md
      - name: Install envsubst
        run: |
          sudo apt update
          sudo apt install -y gettext
      - name: Download push-to-docs script template
        run: |
          curl -o push-to-docs.sh.template https://raw.githubusercontent.com/nevermined-io/reusable-workflows/main/scripts/push-to-docs.sh
      - name: Replace env vars in push-to-docs script
        env:
          BRANCH_TO_CLONE: main
          REPO_TO_PUSH: nvm-docs
          PATH_TO_COPY: docs/
          PATH_TO_PUSH: docs/architecture/node
          REPOSITORY_NAME: ${{ github.repository }}
          API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
        run: |
          export REPOSITORY_NAME=$(echo $REPOSITORY_NAME | awk -F '/' '{print $2}')
          envsubst < push-to-docs.sh.template > push-to-docs.sh
          env > env.file
          chmod +x push-to-docs.sh
          ./push-to-docs.sh
