name: Integration Tests

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '16.x'
      - name: Install dependencies
        run: |
          yarn
      - name: Compile and lint
        run: |
          yarn run build
          yarn run lint
      - name: Check code formatting
        run: yarn format:check
      - uses: nevermined-io/nvm-tools-actions@v0.12.0
        with:
          token: ${{ secrets.API_TOKEN_GITHUB }}
          estuary: 'true'
          node: 'false'
          contracts-version: 'v3.2.1'
      - name: Check artifacts
        run: |
          nvm-tools copy-artifacts ./artifacts
          ls -l artifacts
          nvm-tools copy-circuits ./circuits
          ls -l circuits
      - name: Run node
        run: |
          yarn run setup:dev
          yarn start &

          # wait for node to start
          wget --retry-connrefused --tries=20 http://localhost:8030
      - name: Run tests
        run: |
          # HDWalletProvider keeps jest from exiting
          yarn run integration:cov -- --forceExit
