apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: nevermined-compute-
  namespace: nevermined-compute
spec:
  # To be set by the compute api
  entrypoint:
  workflowMetadata:
    labels:
      # to be set by the compute api
      serviceAgreementId:
  arguments:
    parameters:
      - name: volume
        value: /data
        # The rest of these parameters is to be set by the compute api
        # - name: provider_key_file
        #   value:
        # - name: provider_password
        #   value:
        # - name: consumer_address
        #   value:
        # - name: keeper_url
        #   value:
        # - name: verbose
        #   value:
        # - name: workflow_did
        #   value:
        # - name: marketplace_api_url
        #   value:
        # - name: gateway_url
        #   value:
        # - name: gateway_address
        #   value:
        # - name: transformation_container_image
        #   value:
        # - name: transformation_arguments
        #   value:
        # - name: artifacts_folder
        #   value:
        # - name: circuits_folder
        #   value:
        # - name: input_dir
        #   value:
        # - name: output_dir
        #   value:
        # - name: transformations_dir
        #   value:
  dnsPolicy: ClusterFirstWithHostNet
  hostNetwork: true
  metadata:

  templates:
    - name: coordinator-workflow
      retryPolicy: 'Never'
      dag:
        tasks:
          - name: configurator
            template: configuratorPod

          - name: coordinator
            template: transformationPod-coordinator
            arguments:
              parameters:
                - name: command
                  value: coordinator
                - name: config
                  value: /bin/config-coordinator.toml
            dependencies:
              - configurator

          - name: aggregator
            template: transformationPod-coordinator
            arguments:
              parameters:
                - name: command
                  value: aggregator
                - name: config
                  value: /bin/config-aggregator.toml
            dependencies:
              - configurator

          - name: publishing
            template: publishingPod
            dependencies:
              - coordinator
              - aggregator

    - name: configuratorPod
      container:
        image: neverminedio/compute-pods-config:latest
        imagePullPolicy: IfNotPresent
        name: configurator-pod
        command:
          - sh
          - -cxe
        args:
          - |
            cp -rv /artifacts ./artifacts;
            ./bin/pod-config \
            --workflowId $WORKFLOW_DID;
            ls -lR /data
        env:
          - name: PROVIDER_KEY_FILE
            value: '{{workflow.parameters.provider_key_file}}'
          - name: PROVIDER_PASSWORD
            value: '{{workflow.parameters.provider_password}}'
          - name: KEEPER_URL
            value: '{{workflow.parameters.keeper_url}}'
          - name: WORKFLOW_DID
            value: '{{workflow.parameters.workflow_did}}'
          - name: GATEWAY_URL
            value: '{{workflow.parameters.gateway_url}}'
          - name: GATEWAY_ADDRESS
            value: '{{workflow.parameters.gateway_address}}'
          - name: MARKETPLACE_API_URL
            value: '{{workflow.parameters.marketplace_api_url}}'
          - name: ARTIFACTS_FOLDER
            value: '{{workflow.parameters.artifacts_folder}}'
          - name: CIRCUITS_FOLDER
            value: '{{workflow.parameters.circuits_folder}}'
          - name: BASE_PATH
            value: '{{workflow.parameters.volume}}'
          - name: INPUT_DIR
            value: '{{workflow.parameters.input_dir}}'
          - name: OUTPUT_DIR
            value: '{{workflow.parameters.output_dir}}'
          - name: TRANSFORMATIONS_DIR
            value: '{{workflow.parameters.transformations_dir}}'
          - name: VERBOSE
            value: '{{workflow.parameters.verbose}}'
        volumeMounts:
          - mountPath: /data
            name: workdir
          - mountPath: /artifacts
            name: artifacts-volume

    - name: transformationPod-coordinator
      inputs:
        parameters:
          - name: config
          - name: command
      container:
        image: keykoio/xain-fl:latest
        imagePullPolicy: IfNotPresent
        name: xain-fl
        args:
          - -c
          - '{{inputs.parameters.config}}'
        command:
          - '{{inputs.parameters.command}}'
        env:
          - name: VOLUME
            value: '{{workflow.parameters.volume}}'
          - name: NEVERMINED_INPUTS_PATH
            value: '{{workflow.parameters.volume}}/{{workflow.parameters.input_dir}}'
          - name: NEVERMINED_OUTPUTS_PATH
            value: '{{workflow.parameters.volume}}/{{workflow.parameters.output_dir}}'
          - name: NEVERMINED_TRANSFORMATIONS_PATH
            value: '{{workflow.parameters.volume}}/{{workflow.parameters.transformations_dir}}'
        volumeMounts:
          - mountPath: /data
            name: workdir

    - name: publishingPod
      container:
        image: neverminedio/compute-pods-publish:latest
        imagePullPolicy: IfNotPresent
        name: publishingPod
        command:
          - sh
          - -cxe
        args:
          - |
            cp -rv /artifacts ./artifacts;
            ./bin/pod-publish \
            --workflowId $WORKFLOW_DID \
            --consumerAddress $CONSUMER_ADDRESS;
            ls -lR /data
        env:
          - name: PROVIDER_KEY_FILE
            value: '{{workflow.parameters.provider_key_file}}'
          - name: PROVIDER_PASSWORD
            value: '{{workflow.parameters.provider_password}}'
          - name: CONSUMER_ADDRESS
            value: '{{workflow.parameters.consumer_address}}'
          - name: KEEPER_URL
            value: '{{workflow.parameters.keeper_url}}'
          - name: WORKFLOW_DID
            value: '{{workflow.parameters.workflow_did}}'
          - name: GATEWAY_URL
            value: '{{workflow.parameters.gateway_url}}'
          - name: GATEWAY_ADDRESS
            value: '{{workflow.parameters.gateway_address}}'
          - name: MARKETPLACE_API_URL
            value: '{{workflow.parameters.marketplace_api_url}}'
          - name: ARTIFACTS_FOLDER
            value: '{{workflow.parameters.artifacts_folder}}'
          - name: CIRCUITS_FOLDER
            value: '{{workflow.parameters.circuits_folder}}'
          - name: BASE_PATH
            value: '{{workflow.parameters.volume}}'
          - name: OUTPUT_DIR
            value: '{{workflow.parameters.output_dir}}'
          - name: VERBOSE
            value: '{{workflow.parameters.verbose}}'
        volumeMounts:
          - mountPath: /data
            name: workdir
          - mountPath: /artifacts
            name: artifacts-volume

  volumeClaimTemplates:
    - metadata:
        name: workdir
      spec:
        accessModes:
          - ReadWriteMany
        resources:
          requests:
            storage: 2Gi
  volumes:
    - configMap:
        name: artifacts
      name: artifacts-volume
status: {}
